### ISSUE TITLE
[BUG] message display throws error

### ISSUE THREAD

**Issue by th-2021** [jsuto/piler#149]
1723365989205 TypeError: Cannot read properties of undefined (reading 'backdrop')
    at On._initializeBackDrop (modal.js:160:39)
    at new On (modal.js:71:27)
    at On.getOrCreateInstance (base-component.js:65:41)
    at Object.modal (piler.js:1187:39)
    at Object.<anonymous> (piler.js:245:20)
    at c (jquery-3.7.1.min.js:2:25304)
    at Object.fireWith [as resolveWith] (jquery-3.7.1.min.js:2:26053)
    at l (jquery-3.7.1.min.js:2:77782)
    at XMLHttpRequest.<anonymous> (jquery-3.7.1.min.js:2:80265)

Could this be related to path prefix? Or this this something different?

**Comment by jsuto** [comment]
Possible. How to reproduce it?

**Comment by jsuto** [comment]
No news is good news.

**Comment by th-2021** [comment]
for me it shows up with every click on a message,

**Comment by jsuto** [comment]
Still no info on how to reproduce it. Also can you check if a clean install with no path prefix provides this issue?

**Comment by th-2021** [comment]
I removed the prefix and same result. Message view shows an empty message.

Browser shows: 
1723973988761 TypeError: this._config is undefined
    _initializeBackDrop modal.js:160
    On modal.js:71
    getOrCreateInstance base-component.js:65
    modal piler.js:1187
    view_message piler.js:245
    jQuery 6
    view_message piler.js:234
    view_message_by_pos piler.js:220
    onclick search.php:1
piler.js:64:19

also piler shows: message verification failed

does this help?

**Comment by jsuto** [comment]
Yes, check the mail logs for pilerget problems.

**Comment by th-2021** [comment]
mail.log shows:

2024-08-18T10:02:15.557667+00:00 staging-piler-84f7b79b58-7rbl6 piler-webui[36]: sphinx query: 'INSERT INTO audit1 (ts, email, action, ipaddr, meta_id, description) VALUES(?,?,?,?,?,?)' in 0.00 s, 0 hits, 0 total found
2024-08-18T10:02:15.574414+00:00 staging-piler-84f7b79b58-7rbl6 pilerget[333]: /var/piler/store/00/664/f0/b1/5000000066457e5c0dbcf1e4000133a1f0b1.m: EVP_DecryptFinal()
2024-08-18T10:02:15.592376+00:00 staging-piler-84f7b79b58-7rbl6 piler-webui[36]: sphinx query: 'SELECT tag FROM tag1 WHERE uid=2 AND mid=17346' in 0.00 s, 0 hits, 0 total found
2024-08-18T10:02:15.593180+00:00 staging-piler-84f7b79b58-7rbl6 piler-webui[36]: sphinx query: 'SELECT note FROM note1 WHERE uid=2 AND mid=17346' in 0.00 s, 0 hits, 0 total found

**Comment by jsuto** [comment]
```
/var/piler/store/00/664/f0/b1/5000000066457e5c0dbcf1e4000133a1f0b1.m: EVP_DecryptFinal()
```

My guess is that either the file is corrupt or piler.key has changed, and can't decrypt the message any longer.
